### ISSUE TITLE
Change the alert click event in DefaultAnnotation.tsx.

### ISSUE THREAD

**Issue by moitorrijos** [portabletext/editor#236]
We created a front-end text editor that meets most of the requirements. However, we encountered an issue with annotations. They have a click event that triggers an alert. We want to remove or change this behavior. The `DefaultAnnotation.tsx` component in `packages/editor/src/editor/nodes/` contains the `span` with the click event. We cannot modify it directly. Is there a way to remove or change this click event?

**Comment by christianhg** [comment]
Hi! That's great to hear! You can control how annotations are rendered using the `renderAnnotation` prop. Check out the playground for inspiration: https://github.com/portabletext/editor/blob/871b56e1c09c3533b9484be2ba529f30436164b1/apps/playground/src/editor.tsx#L133
